project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - about.qmd
    - municipalities.qmd
    - townships.qmd
    - pins.qmd
    - townships/*.qmd
    - municipalities/*.qmd
    - "*.qmd"
    - "townships/*.qmd"
    - "municipalities/*.qmd"
    - "!township_report_template.qmd"
    - "!municipality-template.qmd"
    - "!township_report_template.qmd"
    - "!municipality_report_template.qmd"


website:
  title: "PINs to Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: How PINs Relate to Projects
        
      - href: municipalities.qmd
        text: By Municipality
        
      - href: townships.qmd
        text: By Township

        
      - href: pins.qmd
        text: Search PINs/Projects
  page-footer:
    center: "Cook County commercial and industrial property projects"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: true
    df-print: paged
    link-external-newwindow: true

execute:
  freeze: auto
